CREATE TABLE [rqs].[RequestedGroup]
(
	[ID] INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	[RequestID] INT NOT NULL,
	[GroupID] INT,
	[GroupName] NVARCHAR(64),
	[GroupStatusID] INT NOT NULL,
	[ActiveStatusID] INT NOT NULL,
	[DLM] DATETIME2 NOT NULL DEFAULT(GETDATE())
)